/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _debug_font_h_
#define _debug_font_h_
//---------------------------------------------------------------------------------
extern const unsigned char debug_font[];
extern const int debug_font_size;
//---------------------------------------------------------------------------------
#endif //_debug_font_h_
//---------------------------------------------------------------------------------
